import Foundation

// MARK: - Parental Sharing Configuration

struct ParentalSharingSettings: Codable {
    var isEnabled: Bool = false
    var shareDate: Date?
    var sharedWith: [SharedContact] = []
    var sharingPreferences: SharingPreferences = SharingPreferences()

    struct SharedContact: Identifiable, Codable {
        var id = UUID()
        var name: String
        var relationship: String
        var shareMethod: ShareMethod

        enum ShareMethod: String, Codable {
            case email = "Email"
            case sms = "Text Message"
            case inPerson = "In Person"
        }
    }

    struct SharingPreferences: Codable {
        var shareMoodTrends: Bool = true
        var shareMoodNotes: Bool = false  // Always false for privacy
        var shareTags: Bool = true
        var includeTimestamp: Bool = true
        var shareFrequency: ShareFrequency = .manual

        enum ShareFrequency: String, Codable, CaseIterable {
            case manual = "Manual Only"
            case weekly = "Weekly"
            case biweekly = "Every 2 Weeks"
            case monthly = "Monthly"
        }
    }
}

// MARK: - Mood Summary for Sharing

struct MoodSummary {
    let dateRange: String
    let totalEntries: Int
    let moodBreakdown: [String: Int]
    let topTags: [String]
    let averageMood: String
    let trendDirection: TrendDirection

    enum TrendDirection {
        case improving
        case stable
        case declining
        case insufficient
    }

    func generateShareableText() -> String {
        var text = "Mood Summary\n"
        text += "Generated: \(Date().formatted())\n\n"
        text += "Date Range: \(dateRange)\n"
        text += "Total Entries: \(totalEntries)\n\n"

        text += "Mood Breakdown:\n"
        for (mood, count) in moodBreakdown.sorted(by: { $0.value > $1.value }) {
            let percentage = Double(count) / Double(totalEntries) * 100
            text += "  \(mood): \(count) (\(String(format: "%.0f", percentage))%)\n"
        }

        if !topTags.isEmpty {
            text += "\nCommon Tags:\n"
            for tag in topTags {
                text += "  • \(tag)\n"
            }
        }

        text += "\nOverall Trend: \(trendDescription)\n"

        text += "\n---\n"
        text += "Notes are private and not included in this summary.\n"
        text += "Generated by StressMind app.\n"

        return text
    }

    private var trendDescription: String {
        switch trendDirection {
        case .improving:
            return "Improving - More positive moods recently"
        case .stable:
            return "Stable - Consistent mood patterns"
        case .declining:
            return "Concerning - More difficult moods recently. Consider professional support."
        case .insufficient:
            return "Insufficient data to determine trend"
        }
    }
}

// MARK: - Emergency Alert

struct EmergencyAlert: Identifiable {
    let id = UUID()
    let triggerDate: Date
    let reason: AlertReason
    let message: String

    enum AlertReason {
        case severeDistress
        case userRequested
        case multipleNegativeMoods
    }
}
